# Action Info: https://github.com/marketplace/actions/yamllint-github-action
name: 'Yamllint GitHub Actions'
on:
  - pull_request
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Get changed file names'
        
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          # yamllint_file_or_dir: ${{ git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
