# Action Info: https://github.com/marketplace/actions/yamllint-github-action
name: 'Yamllint GitHub Actions'
on:
  - pull_request
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        #uses: actions/checkout@master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get changed file names'
        id: checkForChanges
        run: |
          echo "::set-output name=grepValue::$( git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -c '^proxy' )"
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          #yamllint_file_or_dir: 'goodyml.yml'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
